# MoveIt uses this configuration for controller management
trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

controller_names:
  - arm_controller
  - finger1_controller
  - finger2_controller

arm_controller:
  type: FollowJointTrajectory
  action_ns: follow_joint_trajectory
  default: true
  joints:
    - joint1
    - joint2
    - joint3
finger1_controller:
  type: GripperCommand
  joints:
    - finger_joint1
  action_ns: gripper_cmd
  default: true
finger2_controller:
  type: GripperCommand
  joints:
    - finger_joint2
  action_ns: gripper_cmd
  default: true
